spring:
  profiles:
    active: local

---

spring:
  profiles: local
  kafka:
    template:
      default-topic: testTopic7777
    producer:
#      bootstrap-servers: 192.168.50.201:9092,192.168.50.201:9093,192.168.50.201:9094
      bootstrap-servers: kafka:9092
      key-serializer: org.apache.kafka.common.serialization.IntegerSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer
      properties:
        acks: 0
        retries: 10
        retry.backoff.ms: 1000

    admin:
      properties:
        bootstrap.servers: localhost:9092

---

spring:
  profiles: dev
  kafka:
    producer:
      bootstrap-servers: dev:9092
      key-serializer: org.apache.kafka.common.serialization.IntegerSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer

---

spring:
  profiles: prod
  kafka:
    producer:
      bootstrap-servers: prod:9092
      key-serializer: org.apache.kafka.common.serialization.IntegerSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer
